name: OpenShift

env:
  APP_NAME: "examplevotingapp_vote"
  IMAGE_REGISTRY: "aroacrhackthon.azurecr.io"
  IMAGE_TAGS: "latest"
on:
  push:
    branches: [ master ]

jobs:
  openshift-ci-cd:
    name: Build and deploy on Self-Hosted OpenShift Runners
    runs-on: [ self-hosted, openshift, node ] 
    environment: production

    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:         
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - uses: azure/docker-login@v1
      with:
        login-server: yourACRname.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build . -t ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAGS }}
        docker push ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAGS }}
